# Welcome to Jekyll!
#
# This config file is for settings affecting the entire site. Modify as needed and restart the server for changes.

# Basic Site Settings
locale                   : "en-US"
title                    : "Md. Sajjad Hossain"
title_separator          : "-"
name                     : &name "Md. Sajjad Hossain"
description              : &description "CS undergrad interested in NLP, LLMs, and BNLP"
url                      : "https://5hawon.github.io"  # Your GitHub Pages URL
baseurl                  : ""  # Leave blank for the root of the repository
repository               : "5hawon/5hawon.github.io"  # GitHub repository name

# Site Author
author:
  avatar                 : "profile.png"  # Path to your profile image
  name                   : "Md. Sajjad Hossain"
  bio                    : "Final-year CS undergrad currently doing my thesis."
  location               : "Chittagong, Bangladesh"
  employer               : "Chittagong University of Engineering and Technology"
  email                  : "your-email@example.com"
  linkedin               : "5hawon"  # Your LinkedIn username
  github                 : "5hawon"  # Your GitHub username

# Analytics
analytics:
  provider               : "google-analytics-4"
  google:
    tracking_id          : "G-YOUR_TRACKING_ID"

# SEO Related
google_site_verification : "YOUR_GOOGLE_VERIFICATION_CODE"

# Social Profiles
social:
  type                   : "Person"
  name                   : "Md. Sajjad Hossain"
  links:
    - "https://github.com/5hawon"
    - "https://linkedin.com/in/5hawon"

# Site Settings
teaser                   :  # Default fallback teaser image in /images/
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled" 
comments:
  provider               : false  # Example: "disqus"

# Markdown and Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  toc_levels: 1..6

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Outputting
permalink: /:categories/:title/
timezone: Asia/Dhaka

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
